Task2
Elenaz441/MuseumBot pull request #22
Opened 2023-12-12 06:44 UTC by Elenaz441

2023-12-13 19:50 UTC, vpyzhyanov requested changes
В целом очень хорошо. Но есть замечания.

**Очень критичное замечание:** Нет тестов на `CommandContainer`

Я могу сделать вашего бота полностью неработоспособным так:

![image](https://github.com/Elenaz441/MuseumBot/assets/71599019/6077be93-cc16-4aa7-bbc1-cff69d3b232e)


Но тесты будут по прежнему проходить.

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/Executable.java
> +public interface Executable {
где JavaDoc?

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/ExecutableWithState.java
> +public interface ExecutableWithState extends Executable {
интересный ход)

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/ExecutableWithState.java
> +     * @return состояние
плохое описание, ничего не понятно. Лучше опишите зачем этот метод нужен и что это за состояние, для чего используется. Мне пришлось копаться в иерархии вызовов, чтобы это понять. А должен был сразу понять как прочитал описание.

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/LeaveReviewCommand.java
> +    static final String NO_EVENT = "У вас нет мероприятий, которые можно оценить.";
1. нехорошо смешить константы и остальные поля. Отделите их друг от друга пустой строкой и поместите группу констант рядом друг с другом.
2. Нарушена икапсуляция для всех констант. Все они используются **только** в этом классе и они почему-то не private

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/PreRateNonCommand.java
> +    public static final String RATE_PREV_MESSAGE = "Как вы оцениваете данное мероприятие от 0 до 10," +
аналогично

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/PreRateNonCommand.java
> +        Long eventId = Long.valueOf(args.getCallbackData().split(" ")[1]);
а где обработка ошибок? А если не получится привести строку к числу?

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/PreViewExhibitCommand.java
> +    static  final String IF_NO_EXHIBIT_BY_MUSEUM = "Извините," +
то же самое. И сервисы смешаны с константами и область видимость констант неправильная.

Да ещё и форматирование страдает. Вон лишние пробелы затесались

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/PreViewMuseumsRankCommand.java
> +        return museumService.getMuseums();
однострочный метод не имеет смысла

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/State.java
> +public enum State {
где JavaDoc?

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/ViewExhibitCommand.java
> +public class ViewExhibitCommand implements Command {
где JavaDoc?

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/State.java
> +    private static final Map<String, State> ENUM_MAP;
вы думали я не замечу? static запрещён

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/State.java
> +    static {
static запрещён

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/State.java
> +    public static State get (String stateString) {
static запрещён

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/State.java
> +    State(String stateString) {
всё слеплено в одну кучу. Добавьте пустых строк, отделите поля от методов. Сгруппируйте поля с полями и методы с методами. Сначала идут значения enum, потом поля, потом конструктор, потом методы.

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/customException/UserInputException.java
> +public class UserInputException extends Exception {
где JavaDoc?

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/dataFormat/ExhibitFormat.java
> +public class ExhibitFormat {
где JavaDoc?

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/models/Museum.java
> +                "\nОписание: " + description;
Опять логика в toString?

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/models/Review.java
> +                "\nОтзыв: " + review;
Опять логика в toString?

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/repository/MuseumRepository.java
> +    Museum getMuseumById(Long id);
не забывайте JavaDoc ко всем методам интерфейса

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/repository/ExhibitRepository.java
> +    Exhibit getExhibitById(Long id);
не забывайте JavaDoc ко всем методам интерфейса

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/repository/ReviewRepository.java
>      Review getReviewByUserAndEvent(User user, Event event);
не забывайте JavaDoc ко всем методам интерфейса

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/service/ExhibitService.java
> +            return  eventRepository.getEventById(eventId).getMuseum().getExhibits();
форматирование съехало куда-то

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/service/ExhibitService.java
> +        return exhibitRepository.getExhibitById(id);
весь этот класс не имеет никакого смысла, он тупо делегирует свою работу другому сервису, а сам бьёт баклуши.  Либо наполните его смыслом (какой-то логикой), либо удалите за ненадобностью. Например можно поручить ему форматировать элементы, то есть делать `new ExhibitFormat().toFormattedString` внутри сервиса

2023-12-13 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/service/UserService.java
> +        Instant now = new Date().toInstant();
Посредники не нужны. Просто `Instant.now()`

2023-12-13 19:50 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/LeaveReviewCommandTest.java
> +        Mockito.verify(userService, Mockito.never()).updateUserState(1L, State.RATE_PREV);
неправильно. Логика должна быть такой:

- Если мы проверяем, что метод вызывался, то мы стараемся точно указать аргументы, при которых он вызывался
- Если мы проверяем, что метод **НЕ** вызывался, то мы проверяем, что он не вызывался с **любыми** аргументами

2023-12-13 19:50 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/PreRateNonCommandTest.java
> +    User user;
Про модификаторы видимости не забывайте, пожалуйста

2023-12-13 19:50 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/PreViewMuseumsCommandTest.java
> +    List<Museum> museums;
здесь тоже и далее везде

2023-12-13 19:50 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/jpa/service/UserServiceTest.java
> +        Instant now = new Date().toInstant();
тоже посредники не нужны

2023-12-15 09:43 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/commands/Executable.java
> +public interface Executable {
Исправили все замечания с JavaDoc

2023-12-15 09:44 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/commands/LeaveReviewCommand.java
> +    static final String NO_EVENT = "У вас нет мероприятий, которые можно оценить.";
Исправили все подобные замечания

2023-12-15 09:44 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/commands/PreRateNonCommand.java
> +        Long eventId = Long.valueOf(args.getCallbackData().split(" ")[1]);
Добавили обработку ошибок

2023-12-15 09:45 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/commands/PreViewMuseumsRankCommand.java
> +        return museumService.getMuseums();
Исправили (убрали этот метод)

2023-12-15 09:45 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/commands/State.java
> +    private static final Map<String, State> ENUM_MAP;
Убрали static в этом классе

2023-12-15 09:48 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/jpa/models/Museum.java
> +                "\nОписание: " + description;
Логика в со строками реализована через соответствующие классы в пакете dataFormat и используем мы именно функции из этого пакета. Просто здесь сам toString так реализован

2023-12-15 09:54 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/jpa/service/ExhibitService.java
> +        return exhibitRepository.getExhibitById(id);
Исправили, добавили форматирование строки

2023-12-15 09:54 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/jpa/service/UserService.java
> +        Instant now = new Date().toInstant();
Исправили подобные замечания

2023-12-15 09:54 UTC, Elenaz441 commented on src/test/java/ru/urfu/museumbot/commands/LeaveReviewCommandTest.java
> +        Mockito.verify(userService, Mockito.never()).updateUserState(1L, State.RATE_PREV);
Исправили

2023-12-15 09:55 UTC, Elenaz441 commented on src/test/java/ru/urfu/museumbot/commands/PreRateNonCommandTest.java
> +    User user;
Исправили

2023-12-16 19:09 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/PreRateNonCommand.java
> +    private static final String NUMBER_FORMAT_EXCEPTION_TEXT = "Извините, не смог найти событие.";
имя константы и её содержимое сильно отличаются друг от другуа

2023-12-16 19:09 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/PreRateNonCommand.java
> +            System.out.println(String.format("Не удалось привести CallBackData к числу %s", e.getMessage()));
А вы не хотите пользователю что-нибудь ответить в этом случае, а то он получит только `"Извините, не смог найти событие."`

2023-12-16 19:09 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/ViewMuseumRankCommand.java
> +        if (reviews.size() == 0) {
лучше `isEmpty()`

2023-12-16 19:09 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/customException/UserInputException.java
> + * Кастомный класс исключения на некорректный ввод пользователя
> Кастомный класс исключения

Не надо воды

Судя по описание класс должен называться `IncorrectUserInputException`

2023-12-16 19:09 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/models/Museum.java
> +                "\nОписание: " + description;
А зачем убрали тогда? toSting лучше генерировать с помощью среды разработки

2023-12-16 19:21 UTC, vpyzhyanov requested changes
Почему одни и те же замечания приходится писать второй раз?!

Замечание про Mockito.never() исправьте везде, пожалуйста. И код начинайте с JavaDoc, так вы точно его не забудете.

В целом критичных замечаний нет, вы молодцы. Задачу принял. Как исправите последние замечания, можете мёрджить.

2023-12-16 19:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/PreRateNonCommandTest.java
>      UserService userService;
Пропустили модификатор видимости

2023-12-16 19:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/PreRateNonCommandTest.java
> +        Mockito.verify(userService, Mockito.never()).setReviewingEvent(1L, 1L);
ну я же уже рассказывал как правильно делать. Почему опять на эти же грабли наступаете?

2023-12-16 19:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/PreViewMuseumsCommandTest.java
>      MuseumService museumService;
А это поле чем хуже? Оно недостойно исправления замечания?

2023-12-16 19:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/jpa/service/ExhibitServiceTest.java
> +    public void getFormattedString() {
где JavaDoc и форматирование?

Почему одни и те же замечания приходится писать второй раз?!

2023-12-18 08:57 UTC, merged