Task1
Elenaz441/MuseumBot pull request #7
Opened 2023-11-17 06:34 UTC by Elenaz441

2023-11-20 18:54 UTC, vpyzhyanov commented
Сборка не прошла
![image](https://github.com/Elenaz441/MuseumBot/assets/71599019/44f92372-f8db-49ae-9b17-afb47531cb4c)

2023-11-20 19:04 UTC, vpyzhyanov commented
Тесты не должны поднимать спринговый контекст. Тем более, когда ни одного теста в классе нет!
![image](https://github.com/Elenaz441/MuseumBot/assets/71599019/ee2d713e-bd70-440e-bc94-d5596e2c70d7)

2023-11-20 20:15 UTC, vpyzhyanov requested changes
В целом сделали хорошо, молодцы! Но есть замечания.

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/GUI/Widgets.java
> +package ru.urfu.museumbot.GUI;
имена пакетов принято писать маленькими буквами

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/GUI/Widgets.java
> + * <p>предоставляет активные элементы для оботражения сообщений от бота</p>
опечатка в слове "отображения". Поставьте русский словарь в IDEA и она будет сама подсказывать ошибки в словах

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/GUI/Widgets.java
> +    public static Map<String, String> description = Map.ofEntries(
1. static запрещён
2. Нарушена инкапсуляция

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/GUI/Widgets.java
> +public class Widgets {
Имя класса (да и пакета) выбрано не совсем удачно. Вы использовали термины из интерфейса пользователя, которые в вашему функционалу не имеют никакого отношения. Весь GUI содержится в телеграмме. Ваш код отрисовкой не занимается. В данном контексте кнопки - это не GUI, это набор данных для кнопок.

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/GUI/Widgets.java
> +            entry(START, "Старт"),
entry не нужен, он просто посредник. Можно было сразу `new BotCommand` делать

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfig.java
> +    public TelegramBot registration(TelegramBot bot){
метод выглядит очень странно. Он возвращает ровно то, что пришло в качестве аргумента.

Но давайте по порядку:

1. `@Configuration` - это специальный класс, который служит одной цели - **создать бины**, которые требуют особой настройки и не могут создать себя сами.
2. Все методы этого класса должны создавать бины и иметь соответствующие методы. Например в данном случае метод должен называться `telegramBot`
3. Этот метод не создаёт никакой бин, а тупо возвращает подтянутую зависимость. А должен создать `TelegramBot`, т.е. вызывать его конструктор. Значит в качестве аргумента метода должен быть `BotLogic logic`

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfig.java
> +public class BotConfig {
Слово `Config` обычно обозначает настройки. Например, настройки пользователя или приложения. Но здесь не этот смысл. Здесь это `Configuration`, это уже термин Spring'а. Поэтому имя класса должно быть `BotConfiguration`

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfig.java
> +            e.printStackTrace();
у вас проект - телеграмм бот, поэтому странно, что приложение нормально поднимается, даже если не удалось запустить бота. Здесь надо обернуть исключение в своё (например, Exception или RuntimeException) с человекочитаемым сообщением.

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/BotLogic.java
> +import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.InlineKeyboardButton;
неиспользуемые импорты

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/TelegramBot.java
> +    @Value("${bot.name}")
Эти поля тоже должны определяться в конструкторе. Иначе невозможно будет их использовать в конструкторе, даже если вы захотите.

Нельзя смешивать способ инжекта бинов, нужно выбрать какой-то один. Либо через поля, либо через конструктор. Рекомендую через конструктор.

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/TelegramBot.java
> +    String botName;
нарушена инкапсуляция

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/TelegramBot.java
> +        this.logic = logic;
хоть вы и не вызвали конструктор явно, но но всё равно вызывается по умолчанию. А он помечен **deprecated**. Вызывайте правильный конструктор! 

IDEA же вам подсвечивает проблему, почему не исправили?

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/TelegramBot.java
> +@Component
Если будете создавать бин через конфигурацию, то эта аннотация будет не нужна

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/StaticText.java
> +    static String HELP_TEXT = """
static запрещён

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/BotLogic.java
> +        message.setChatId(chatId);
Обратите внимание, что вы в каждом методе устанавливаете chatId. Представляете что будет если хоть в одном методе забыть его определить?

Да и вообще описание метода говорит `Отменить запись пользователя на мероприятия`, но оказывается, что метод не только отменяет запись, но формирует ответное сообщение, включая логику заполнения этого сообщения. Добро пожаловать на тёмную сторону ООП.

За формирование `handleIncomingTextMessage` должен отвечать только `handleIncomingTextMessage` и никто больше

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/BotLogic.java
> +            case START -> message = startCommandReceived(chatId, username);
было бы здорово иметь на каждую команду отдельный обработчик (в отдельном классе). Тогда у `BotLogic` не было бы лишних зависимостей от сервисов (eventService, userService, reviewService).

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/models/Event.java
> +package ru.urfu.museumbot.JPA.models;
пакеты именуются маленькими буквами

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +        return eventRepository.findAll().stream().filter(event -> event.getDate().
какова сложность этого метода? На самом деле непозволительно большая. Нужно фильтры в репозиторий поместить.

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +                .sorted(Comparator.comparing(Event::getDate))
И сортировка данных тоже должна быть в репозитории

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +    public static final int AMOUNT_TO_ADD_DATE = 7;
static запрещён

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +     * <p>Получить список ближайших мероприятий</p>
"ближайших" - это каких?

2023-11-20 20:15 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/BotLogicTest.java
> +        List<Event> events = getEvents();
1. Это не **get**, это **create**. Разница ощутимая, либо мы создаём новые объекты, либо берём готовые.
2. Готовить тестовые данные в отдельном методе не очень оптимально. Лучше их создать в конструкторе и сохранить в поле класса. Так все тесты смогут ими пользоваться и не создавать по несколько раз.

2023-11-20 20:15 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/BotLogicTest.java
> +        assertEquals(events.get(0) + "\n\n===============================\n\n" + events.get(1), message.getText());
1. Тест не должен использовать логику основного приложения для получения ожидаемого значения. Тест должен быть записан **явно**
2. Использовать `toString()` можно только в отладочных целях! Нельзя помещать в него логику приложения.

2023-11-20 20:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/models/Event.java
> +        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, d MMMM yyyy, HH:mm");
Использовать `toString()` можно только в отладочных целях! Нельзя помещать в него логику приложения.

2023-11-20 20:15 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/BotLogicTest.java
> +        assertEquals(events.get(0) + "\n\n===============================\n\n" + events.get(1), message.getText());
аналогично

2023-11-20 20:15 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/BotLogicTest.java
> +        assertEquals(2, keyboard.getKeyboard().size());
размер 2, а проверили только одну кнопку

2023-11-20 20:15 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/JPA/service/ReviewServiceTest.java
> +        assertEquals(0, event.getReviews().size());
не проверили, что вызван метод save у обоих объектов

2023-11-20 20:15 UTC, vpyzhyanov commented on pom.xml
> +                <exclusion>
не так я учил работать с зависимостями, не так библиотеки исключать

2023-11-21 17:16 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/commands/BotLogic.java
> +            case START -> message = startCommandReceived(chatId, username);
Имеется в виду, что на каждую команду лучше сделать свой отдельный класс обработки? Разве в таком случае не придется в боте через конструктор определять эти классы?

2023-11-21 17:42 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/JPA/models/Event.java
> +        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, d MMMM yyyy, HH:mm");
То есть в классе стоит создать отдельный метод, который бы приводил данные к нужному виду. И работать уже через этот метод, а не через ```toString()```?

2023-11-21 17:55 UTC, Elenaz441 commented on pom.xml
> +                <exclusion>
Нужно всё обернуть в dependencyManagement, я правильно понимаю?😅

2023-11-23 07:57 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/BotLogic.java
> +            case START -> message = startCommandReceived(chatId, username);
Да, отдельные классы, которые отвечают за каждую отдельную команду.

> Разве в таком случае не придется в боте через конструктор определять эти классы?

Если это будут бины, то придётся. Ну а разве это проблема?

Если вас смущает количество аргументов, то можно создать фабрику, которая на каждую команду будет выдавать обработчик. Но тогда все эти аргументы будут уже в фабрике, так что смысла особо нет так делать.

2023-11-23 08:00 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/models/Event.java
> +        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, d MMMM yyyy, HH:mm");
да. Что-то тип `toFormattedString()`.  Но по хорошему, форматирование - это отдельная независимая задача, которая должна выноситься в отдельный класс. На самом деле ваш класс `Event` прегружен функционалом. Всё равно инкапсуляции в нём никакой нет.

2023-11-23 08:01 UTC, vpyzhyanov commented on pom.xml
> +                <exclusion>
да

2023-11-27 18:50 UTC, vpyzhyanov commented
static запрещён

![image](https://github.com/Elenaz441/MuseumBot/assets/71599019/f63a2a0a-0dbe-486f-b68b-af1c01153ff0)

2023-11-27 19:53 UTC, vpyzhyanov requested changes
Прошу вспомнить что такое "правила хорошего тона", чтобы наше взаимодействие было приятным и плодотворным.
Некоторые замечания не были исправлены, некоторые исправлены не так (проблема осталась)

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/buttons/ButtonsContent.java
> + * <p>класс виджетов</p>
описание не соответствует имени класса

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfig.java
> +    public TelegramBot registration(TelegramBot bot){
Стало лучше, но не совсем. Объясните, пожалуйста, для чего нужен бин `TelegramBotsApi` и как он используется?

Для чего нужен ServiceContext?

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfiguration.java
> +        return new TelegramBot(botToken, botName, serviceContext);
Что помешало тут же зарегистировать бота?

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/service/ServiceContext.java
> +public class ServiceContext {
Сборник сервисов? Зачем? Класс не может существовать без своей задачи.

Удаляйте скорее, пока никто не видит. Не хватало нам ещё контейнера для сервисов!

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/service/SendBotMessageService.java
> +            bot.execute(sendMessage);
добро пожаловать в коллективную безответственность. Задача отправки сообщений есть у этого сервиса и у `TelegramBot`, по этой строчке это очень ярко видно. К тому же `SendMessage` - это часть **телеграмм** бота, то есть ваш сервис совсем не универсален.

А надо было создать интерфейс `Bot` и определить там методы отправки сообщения, которые `TelegramBot` и реализует под себя.

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfig.java
> +            e.printStackTrace();
человекочитаемого исключения не случилось(((

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/TelegramBot.java
> +        this.commandContainer = new CommandContainer(new SendBotMessageService(this), serviceContext);
вроде сервис (т.е. бин), но создаётся как простой смертный (т.е. обычный java класс)

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/TelegramBot.java
> +            System.out.println(e.getMessage());
человекочитамое сообщение, пожалуйста

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/ViewUpcomingEventsCommand.java
> +        this.eventService = serviceContext.getEventService();
Вот пример наиболее неуместного применения serviceContext

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/StaticText.java
> +    static String HELP_TEXT = """
Не исправлено!

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +        return eventRepository.findAll().stream().filter(event -> event.getDate().
Правила хорошего тона предполагаю ответы на вопросы! =(

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +    public static final int AMOUNT_TO_ADD_DATE = 7;
Зачем убрали константу? Теперь ровно эта же константа, но в виде "магического" числа, смысл которого уже не так понятен. В таком случае получайте противоположное замечание: нужно убрать "магические" числа

2023-11-27 19:53 UTC, vpyzhyanov commented on src/test/java/ru/urfu/museumbot/commands/ViewUpcomingEventsCommandTest.java
> +        fakeSender = new FakeSender(telegramBot);
Вот отличный пример, показывающий, что зависимость сервиса отправки сообщения от telegramBot не имеет смысла. Зависимость есть, мок есть, но его поведение нигде не переопределяется и даже не используется. Это к тому, что именно бот должен заниматься отправкой сообщений

2023-11-27 19:53 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/models/Event.java
> +        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, d MMMM yyyy, HH:mm");
что-то вы ни инкапсуляцию не сделали (хотя могли), ни вынесли форматирование в отдельный класс. 

P.S. а если отдельный класс будет вложенным, то можно и инкапсуляцию сделать и класс вынести

2023-11-27 19:53 UTC, vpyzhyanov commented on pom.xml
> +                <exclusion>
что-то пошло не так. И исключения не стало, и работа с зависимостями не как по лекции, и комментария о том, что же произошло нет!

2023-11-28 11:03 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/BotConfig.java
> +    public TelegramBot registration(TelegramBot bot){
TelegramBotsApi регистрирует бота. Да, возможно, это стоит сделать в бине telegramBot. Тогда этот бин (TelegramBotsApi) нужно удалить?

ServiceContext нужен, чтобы не передавать каждый сервис отдельно (чтобы уменьшить количество передаваемых переменных).

2023-11-28 11:06 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +        return eventRepository.findAll().stream().filter(event -> event.getDate().
Не было ответа на вопрос, потому что вроде как вы сами на него ответили и это выглядел как риторический вопрос😅😅

Сейчас фильтр и сортировка реализована через репозиторий.

2023-11-28 11:08 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +    public static final int AMOUNT_TO_ADD_DATE = 7;
Тогда здесь нужно сделать следующее: вернуть константу в EventService и добавить её описание в javaDoc?

2023-11-28 11:10 UTC, Elenaz441 commented on pom.xml
> +                <exclusion>
Нам нужно использовать DependencyManagment, но DependencyManagment используется когда в проекте есть несколько дочерних модулей. Нам нужно создать дочерние модули?

2023-11-28 11:11 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/buttons/ButtonsContent.java
> + * <p>класс виджетов</p>
Описание поправим

2023-11-28 11:14 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/BotConfiguration.java
> +        return new TelegramBot(botToken, botName, serviceContext);
Регистрацией занимается другой бин

2023-11-28 11:15 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/jpa/service/ServiceContext.java
> +public class ServiceContext {
т.е. мы должны в CommandContainer передавать все сервисы? Тогда аргументов в конструкторе станет 5, а в последствии может быть и больше.

2023-11-28 11:16 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/jpa/service/SendBotMessageService.java
> +            bot.execute(sendMessage);
В итоге, нужно сделать следующее: SendMessageService удалить, вынести методы в telegramBot interface Bot: SendMessage, sendMessageWithButtons?

2023-11-28 11:20 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/JPA/models/Event.java
> +        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, d MMMM yyyy, HH:mm");
То есть нужно сделать следующее: форматирование данных выделить во вложенный класс?

2023-11-28 11:26 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/TelegramBot.java
> +            System.out.println(e.getMessage());
Человекочитаемое сообщение, то есть отдельно с помощью System.out.println прописать, почему именно произолшла ошибка. Например, здесь нужно написать следующее: System.out.println("Не получилось установить панель с командами");?

2023-11-28 11:27 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/TelegramBot.java
> +        this.commandContainer = new CommandContainer(new SendBotMessageService(this), serviceContext);
Исправим

2023-11-28 11:32 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/commands/StaticText.java
> +    static String HELP_TEXT = """
Вопрос про static в целом. Почему нельзя использовать статик для констант? Вроде как в этом случае их как раз можно использовать. Или мы что-то путаем?

2023-11-28 17:22 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfig.java
> +    public TelegramBot registration(TelegramBot bot){
> Объясните, пожалуйста, для чего нужен бин TelegramBotsApi и как он используется?

Похоже вы неправильно поняли вопрос. Я прекрасно знаю зачем нужен `TelegramBotsApi`, у него есть прекрасное описание. Я же спросил с какой целью вы сделали его **БИНОМ** и где он используется (хоть в одном месте он используется?)?

> Тогда этот бин (TelegramBotsApi) нужно удалить?

На этот вопрос вам нужно найти ответ самостоятельно. Используйте ваши ответы на мои вопросы, они вам помогут

2023-11-28 17:29 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/StaticText.java
> +    static String HELP_TEXT = """
Хороший вопрос. Нет вы тут ничего не путаете. С одной стороны статик для констант использовать правильно. Но с другой стороны у нас статик запрещён совсем. Я пока не уверен стоит ли разрешить использовать его для всех констант..... в общем, подумаю ещё.

2023-11-28 17:32 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +        return eventRepository.findAll().stream().filter(event -> event.getDate().
ну я же должен понимать, что вы тоже понимаете какая это сложность)) А дожидаться вашего ответа возможно будет долго

2023-11-28 17:33 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/service/EventService.java
> +    public static final int AMOUNT_TO_ADD_DATE = 7;
Если имя константы полностью описывает её смысл, то не нужно делать дополнительный JavaDoc.

2023-11-28 17:40 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/JPA/models/Event.java
> +        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, d MMMM yyyy, HH:mm");
Всё зависит от того будете вы делать инкапсуляцию или нет. Если будете, то можете вынести просто в отдельный класс.

P.S. на самом деле я тут придираюсь и делаю это с одной целью: чтобы вы начали задумываться про разделение ответственности в классах. Маленький метод по форматированию вряд ли стоит вынесения в целый отдельный класс, но задуматься об этом надо. Поэтому лучше вынесите.

2023-11-28 17:43 UTC, vpyzhyanov commented on pom.xml
> +                <exclusion>
> комментария о том, что же произошло нет!

Это до сих пор актуально!!!!

Не забывайте, что мы учимся строить проекты правильно, поэтому применяйте те же правила для проекта из одного модуля. DependencyManagment можно использовать на любом проекте, просто в многомодульном он приобретает ощутимое преимущество

2023-11-28 17:45 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfiguration.java
> +        return new TelegramBot(botToken, botName, serviceContext);
Зачем? А что такое "бин" тогда? И зачем он вам нужен?

Добро пожаловать в коллективную безответственность, бот создаётся в одном месте, а регистрируется в другом.

2023-11-28 18:28 UTC, Elenaz441 commented on pom.xml
> +                <exclusion>
Комментарий о произошедшем: похоже, когда добавили DependencyManagment что-то не так прописали и из-за этого не проходила сборка проекта, решили, что сборка не проходит из-за него и просто убрали exclusions. Сейчас снова попробовали собрать проект с DependencyManagment и с exclusions и сборка прошла.

2023-11-28 19:35 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/service/ServiceContext.java
> +public class ServiceContext {
``Перенёс ваш ответ в более подходящее для этого обсуждения место:

> ServiceContext нужен, чтобы не передавать каждый сервис отдельно (чтобы уменьшить количество передаваемых переменных).

А в итоге вы сделали ещё хуже. Променяли одну тёмную сторону на другую (добавили ненужную абстракцию). Я ведь про контекст рассказывал, в том числе рассказывал и про то в каких случаях его надо применять и какие у него последствия. А последствия в том, что у вас увеличивается количество связей, теперь их не N, а N+1. Хотя именно в этом проблема большого количества аргументов, которую вы должны были решать. И проблему не решили и усугубили её.

> т.е. мы должны в CommandContainer передавать все сервисы? Тогда аргументов в конструкторе станет 5, а в последствии может быть и больше.

Да, нужно передавать все сервисы, которые там **явно используются**. 

**Про то, как сделать ещё лучше**

Вы используете Spring, значит каждая команда может быть сервисом и тянуть только те зависимости, которые ей нужны. А в `CommandContainer ` все команды будут инициализироваться коллекцией:
```
@Autowired
List<Command> beanList;
```

Только в интерфейс Command надо будет добавить метод `getCommandName()`, благодаря которому можно будет создать Map, т.е заполнить её ключи:
`private final Map<String, Command> commandMap;`

2023-11-28 19:36 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/jpa/service/SendBotMessageService.java
> +            bot.execute(sendMessage);
да

2023-11-28 19:38 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/TelegramBot.java
> +            System.out.println(e.getMessage());
Да, всё так, но добавить чуть больше информации

`System.out.println("Не получилось установить панель с командами. Причина: " + e.getMessage());`

2023-11-28 19:39 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/ViewUpcomingEventsCommand.java
> +        this.eventService = serviceContext.getEventService();
у этого класса одна зависимость, но по факту их тут две (одна явно лишняя)

2023-11-28 19:48 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfiguration.java
> +    public TelegramBot telegramBot(@Value("${bot.name}") String botName,
Ещё как вариант можно было навесить на TelegramBot аннотацию `@Component`, а бота регистрировать по событию окончания инициализации приложения (внутри класса TelegramBot):
```
    @EventListener(ContextRefreshedEvent.class)
    public void init() {
        try {
            TelegramBotsApi api = new TelegramBotsApi(DefaultBotSession.class);
            api.registerBot(this);
        } catch (TelegramApiException e) {
            throw new RuntimeException(e);
        }
    }
```

В этом случае вам BotConfiguration вообще не нужен. Всё равно вы не используете его по назначению.

2023-11-30 10:11 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/BotConfig.java
> +            e.printStackTrace();
> Здесь надо обернуть исключение в своё (например, Exception или RuntimeException) с человекочитаемым сообщением.

замечание исправлено только на половину!

2023-11-30 10:32 UTC, vpyzhyanov requested changes
Мне кажется мы начинаем ходить по кругу. Как будь-то я снова пишу те же замечания, которые были в начале.

2023-11-30 10:32 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/TelegramBot.java
> +            System.out.printf("Сообщение не отправилось! Причина: %s", e.getMessage());
> Здесь надо обернуть исключение в своё (например, Exception или RuntimeException) с человекочитаемым сообщением.

замечание исправлено только на половину!

2023-11-30 10:32 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/NonCommand.java
> +@Service
почему это сервис?

2023-11-30 10:32 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/CommandContainer.java
> +                            CancelCommand cancelCommand) {
Ну я же написал как это надо сделать, в чём случилась трудность?

> `List<Command> commands`

2023-11-30 10:32 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/HelpCommand.java
> +        message.setChatId(update.getMessage().getChatId().toString());
мы ведь уже обговаривали, что не надо делать в **каждом** обработчике команды **одинаковые** действия.

2023-11-30 10:32 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/Bot.java
> +    void sendMessage(SendMessage message);
Вы используете класс из библиотеки для телеграмма. Тогда интерфейс следует назвать TelegramBot.... но ведь у вас уже есть такой класс.... проблема)))

Ох и зря вы завязались на телеграмм. Это очень сильно связывает вам руки и заставляет делать плохую нерасширяемую архитектуру. Если мне не изменяет память, мы тоже уже это обсуждали и вот опять(((

Как правильно: создайте свой класс `Message` и поместите туда всё что вам нужно. И текст и кнопки, даже картинки туда можно добавить. А `TelegramBot` пусть сам конвертирует его в свой `SendMessage`

2023-11-30 10:33 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/BotConfig.java
> +            e.printStackTrace();
То есть надо везде использовать Exception/RuntimeException вместо TelegramApiException? Если так, то почему? 

Или где-то просто был пропущен выброс ошибки и не добавлен комментарий?

2023-12-05 10:43 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/Bot.java
> +    void sendMessage(SendMessage message);
Добавили класс `Message`

2023-12-05 10:44 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/commands/CommandContainer.java
> +                            CancelCommand cancelCommand) {
Исправили

2023-12-05 10:44 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/TelegramBot.java
> +            System.out.printf("Сообщение не отправилось! Причина: %s", e.getMessage());
Исправили. Теперь если бот не зарегистрировался, выбрасывает ошибку

2023-12-07 14:01 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/TelegramBot.java
> +            System.out.printf("Сообщение не отправилось! Причина: %s", e.getMessage());
записи в логе будут склеиваться в одну строчку. Нехорошо. Нужно print**LN**

2023-12-07 14:01 UTC, vpyzhyanov commented on src/main/java/ru/urfu/museumbot/commands/NonCommand.java
> +@Service
Нет ответа(

2023-12-07 14:05 UTC, vpyzhyanov requested changes
Исправьте оставшиеся замечания и можете мёрджить. Задача принята.

Не забудьте сделать rebase (или merge) второй задачи от main

2023-12-07 15:25 UTC, Elenaz441 commented on src/main/java/ru/urfu/museumbot/commands/NonCommand.java
> +@Service
Это был сервис, потому что класс наследовался от интерфейса `Command` (а все наследники этого интерфейса у нас являются сервисами). Однако сейчас класс `NonCommand` не сервис, для того чтобы не подтягивался в списке в `CommandContainer`.

2023-12-10 10:47 UTC, merged